-- MySQL Script generated by MySQL Workbench
-- Wed May 16 15:44:57 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `password` CHAR(35) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voluntary`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voluntary` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `password` CHAR(35) NOT NULL,
  `identity` CHAR(10) NULL,
  `born_date` DATE NULL,
  `prim_phone` CHAR(11) NOT NULL,
  `sec_phone` CHAR(11) NULL,
  `email` VARCHAR(255) NOT NULL,
  `bio` TEXT NULL,
  `photo` CHAR(11) NULL,
  `obs` TEXT NULL,
  `score` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `adress`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `adress` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(255) NOT NULL,
  `number` INT NULL,
  `neib` VARCHAR(255) NULL,
  `postal_code` CHAR(8) NOT NULL,
  `compl` VARCHAR(255) NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `claimant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `claimant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `password` CHAR(35) NOT NULL,
  `identity` CHAR(10) NULL,
  `born_date` DATE NULL,
  `prim_phone` CHAR(11) NOT NULL,
  `sec_phone` CHAR(11) NULL,
  `email` VARCHAR(255) NOT NULL,
  `bio` TEXT NULL,
  `foto` CHAR(11) NULL,
  `obs` TEXT NULL,
  `score` DECIMAL(8,2) NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_claimant_adress1_idx` (`adress_id` ASC),
  CONSTRAINT `fk_claimant_adress1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entity`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entity` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `password` CHAR(35) NOT NULL,
  `description` TEXT NULL,
  `fund_date` DATE NULL,
  `prim_phone` CHAR(11) NOT NULL,
  `sec_phone` CHAR(11) NULL,
  `email` VARCHAR(255) NOT NULL,
  `logo` CHAR(11) NULL,
  `obs` TEXT NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `adress_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entity_adress1_idx` (`adress_id` ASC),
  CONSTRAINT `fk_entity_adress1`
    FOREIGN KEY (`adress_id`)
    REFERENCES `adress` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `working_period`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `working_period` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `srart_time` TIME NOT NULL,
  `end_time` TIME NOT NULL,
  `week_days` CHAR(7) NULL,
  `one_date` DATE NULL,
  `entity_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_working_period_entity1_idx` (`entity_id` ASC),
  CONSTRAINT `fk_working_period_entity1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disponibility`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disponibility` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date_time` DATETIME NOT NULL,
  `end_date_time` DATETIME NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `voluntary_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disponibilidade_voluntary1_idx` (`voluntary_id` ASC),
  CONSTRAINT `fk_disponibilidade_voluntary1`
    FOREIGN KEY (`voluntary_id`)
    REFERENCES `voluntary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `help`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `help` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sol_date_time` DATETIME NOT NULL,
  `fin_date_time` DATETIME NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `help_status` INT NOT NULL,
  `help_type` INT NOT NULL,
  `calimant_score` INT NULL,
  `helper_score` INT NULL,
  `voluntary_id` INT NOT NULL,
  `claimant_id` INT NOT NULL,
  `entity_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_help_voluntary1_idx` (`voluntary_id` ASC),
  INDEX `fk_help_claimant1_idx` (`claimant_id` ASC),
  INDEX `fk_help_entity1_idx` (`entity_id` ASC),
  CONSTRAINT `fk_help_voluntary1`
    FOREIGN KEY (`voluntary_id`)
    REFERENCES `voluntary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_help_claimant1`
    FOREIGN KEY (`claimant_id`)
    REFERENCES `claimant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_help_entity1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resume` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  `date_time` DATETIME NOT NULL,
  `resp_date_time` DATETIME NULL,
  `help_id` INT NOT NULL,
  `voluntary_id` INT NOT NULL,
  `entity_id` INT NOT NULL,
  `claimant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_help1_idx` (`help_id` ASC),
  INDEX `fk_feedback_voluntary1_idx` (`voluntary_id` ASC),
  INDEX `fk_feedback_entity1_idx` (`entity_id` ASC),
  INDEX `fk_feedback_claimant1_idx` (`claimant_id` ASC),
  CONSTRAINT `fk_feedback_help1`
    FOREIGN KEY (`help_id`)
    REFERENCES `help` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_voluntary1`
    FOREIGN KEY (`voluntary_id`)
    REFERENCES `voluntary` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_entity1`
    FOREIGN KEY (`entity_id`)
    REFERENCES `entity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_claimant1`
    FOREIGN KEY (`claimant_id`)
    REFERENCES `claimant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
