-- MySQL Script generated by MySQL Workbench
-- Tue May  8 20:24:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `login` VARCHAR(255) NOT NULL,
  `senha` CHAR(35) NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `voluntario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `voluntario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `senha` CHAR(35) NOT NULL,
  `rg` CHAR(10) NULL,
  `data_nasc` DATE NULL,
  `telefone_prim` CHAR(11) NOT NULL,
  `telefone_sec` CHAR(11) NULL,
  `email` VARCHAR(255) NOT NULL,
  `bio` TEXT NULL,
  `foto` CHAR(11) NULL,
  `obs` TEXT NULL,
  `classificacao` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `requerente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `requerente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `cpf` CHAR(11) NOT NULL,
  `senha` CHAR(35) NOT NULL,
  `rg` CHAR(10) NULL,
  `data_nasc` DATE NULL,
  `telefone_prim` CHAR(11) NOT NULL,
  `telefone_sec` CHAR(11) NULL,
  `email` VARCHAR(255) NOT NULL,
  `bio` TEXT NULL,
  `foto` CHAR(11) NULL,
  `obs` TEXT NULL,
  `classificacao` DECIMAL(8,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `entidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `entidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `razao_social` VARCHAR(255) NOT NULL,
  `cnpj` CHAR(14) NOT NULL,
  `senha` CHAR(35) NOT NULL,
  `descricao` TEXT NULL,
  `data_fund` DATE NULL,
  `telefone_prim` CHAR(11) NOT NULL,
  `telefone_sec` CHAR(11) NULL,
  `email` VARCHAR(255) NOT NULL,
  `logo` CHAR(11) NULL,
  `obs` TEXT NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` CHAR(2) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `estado_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado`
    FOREIGN KEY (`estado_id`)
    REFERENCES `estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` INT NULL,
  `bairro` VARCHAR(255) NULL,
  `cep` CHAR(8) NOT NULL,
  `complemento` VARCHAR(255) NULL,
  `cidade_id` INT NOT NULL,
  `voluntario_id` INT NULL,
  `requerente_id` INT NULL,
  `entidade_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC),
  INDEX `fk_endereco_voluntario1_idx` (`voluntario_id` ASC),
  INDEX `fk_endereco_requerente1_idx` (`requerente_id` ASC),
  INDEX `fk_endereco_entidade1_idx` (`entidade_id` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_voluntario1`
    FOREIGN KEY (`voluntario_id`)
    REFERENCES `voluntario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_requerente1`
    FOREIGN KEY (`requerente_id`)
    REFERENCES `requerente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_entidade1`
    FOREIGN KEY (`entidade_id`)
    REFERENCES `entidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horario_funcionamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horario_funcionamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hora_ini` TIME NOT NULL,
  `hora_fim` TIME NOT NULL,
  `dias_sem` CHAR(7) NULL,
  `data_esp` DATE NULL,
  `entidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_horario_funcionamento_entidade1_idx` (`entidade_id` ASC),
  CONSTRAINT `fk_horario_funcionamento_entidade1`
    FOREIGN KEY (`entidade_id`)
    REFERENCES `entidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `disponibilidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `disponibilidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora_ini` DATETIME NOT NULL,
  `data_hora_fim` DATETIME NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `voluntario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disponibilidade_voluntario1_idx` (`voluntario_id` ASC),
  CONSTRAINT `fk_disponibilidade_voluntario1`
    FOREIGN KEY (`voluntario_id`)
    REFERENCES `voluntario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ajuda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ajuda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data_hora_solicitacao` DATETIME NOT NULL,
  `data_hora_finalizacao` DATETIME NULL,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `requerente_id` INT NULL,
  `entidade_id` INT NULL,
  `voluntario_id` INT NULL,
  `status_ajuda` INT NOT NULL,
  `tipo_ajuda` INT NOT NULL,
  `classif_requerente` INT NULL,
  `classif_ajudante` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ajuda_requerente1_idx` (`requerente_id` ASC),
  INDEX `fk_ajuda_entidade1_idx` (`entidade_id` ASC),
  INDEX `fk_ajuda_voluntario1_idx` (`voluntario_id` ASC),
  CONSTRAINT `fk_ajuda_requerente1`
    FOREIGN KEY (`requerente_id`)
    REFERENCES `requerente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ajuda_entidade1`
    FOREIGN KEY (`entidade_id`)
    REFERENCES `entidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ajuda_voluntario1`
    FOREIGN KEY (`voluntario_id`)
    REFERENCES `voluntario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `feedback` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `resumo` VARCHAR(255) NOT NULL,
  `texto` TEXT NOT NULL,
  `data_hora` DATETIME NOT NULL,
  `data_hora_resposta` DATETIME NULL,
  `entidade_id` INT NULL,
  `requerente_id` INT NULL,
  `voluntario_id` INT NULL,
  `ajuda_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_feedback_entidade1_idx` (`entidade_id` ASC),
  INDEX `fk_feedback_requerente1_idx` (`requerente_id` ASC),
  INDEX `fk_feedback_voluntario1_idx` (`voluntario_id` ASC),
  INDEX `fk_feedback_ajuda1_idx` (`ajuda_id` ASC),
  CONSTRAINT `fk_feedback_entidade1`
    FOREIGN KEY (`entidade_id`)
    REFERENCES `entidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_requerente1`
    FOREIGN KEY (`requerente_id`)
    REFERENCES `requerente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_feedback_voluntario1`
    FOREIGN KEY (`voluntario_id`)
    REFERENCES `voluntario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
  CONSTRAINT `fk_feedback_ajuda1`
    FOREIGN KEY (`ajuda_id`)
    REFERENCES `ajuda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
