package com.si.pinmyhelp.model;
// Generated 17/05/2018 15:02:51 by Hibernate Tools 4.3.1


import com.si.pinmyhelp.model.data.Model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Feedback generated by hbm2java
 */
@javax.persistence.Entity
@Table(name="feedback",catalog="pinmyhelp")
public class Feedback  extends Model {

    private Claimant claimant;
    private Entity entity;
    private Help help;
    private Voluntary voluntary;
    private String resume;
    private String text;
    private Date dateTime;
    private Date respDateTime;

    public Feedback() {
    }
	
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="claimant_id", nullable=false)
    public Claimant getClaimant() {
        return this.claimant;
    }
    
    public void setClaimant(Claimant claimant) {
        this.claimant = claimant;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_id", nullable=false)
    public Entity getEntity() {
        return this.entity;
    }
    
    public void setEntity(Entity entity) {
        this.entity = entity;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="help_id", nullable=false)
    public Help getHelp() {
        return this.help;
    }
    
    public void setHelp(Help help) {
        this.help = help;
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="voluntary_id", nullable=false)
    public Voluntary getVoluntary() {
        return this.voluntary;
    }
    
    public void setVoluntary(Voluntary voluntary) {
        this.voluntary = voluntary;
    }
    
    @Column(name="resume", nullable=false)
    public String getResume() {
        return this.resume;
    }
    
    public void setResume(String resume) {
        this.resume = resume;
    }
    
    @Column(name="text", nullable=false, length=65535)
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_time", nullable=false, length=19)
    public Date getDateTime() {
        return this.dateTime;
    }
    
    public void setDateTime(Date dateTime) {
        this.dateTime = dateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="resp_date_time", length=19)
    public Date getRespDateTime() {
        return this.respDateTime;
    }
    
    public void setRespDateTime(Date respDateTime) {
        this.respDateTime = respDateTime;
    }

}


