package com.si.pinmyhelp.model;
// Generated 17/05/2018 15:02:51 by Hibernate Tools 4.3.1


import com.si.pinmyhelp.model.data.Model;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkingPeriod generated by hbm2java
 */
@javax.persistence.Entity
@Table(name="working_period",catalog="pinmyhelp")
public class WorkingPeriod  extends Model {

    private Entity entity;
    private Date srartTime;
    private Date endTime;
    private String weekDays;
    private Date oneDate;

    public WorkingPeriod() {
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="entity_id", nullable=false)
    public Entity getEntity() {
        return this.entity;
    }
    
    public void setEntity(Entity entity) {
        this.entity = entity;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="srart_time", nullable=false, length=8)
    public Date getSrartTime() {
        return this.srartTime;
    }
    
    public void setSrartTime(Date srartTime) {
        this.srartTime = srartTime;
    }

    @Temporal(TemporalType.TIME)
    @Column(name="end_time", nullable=false, length=8)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="week_days", length=7)
    public String getWeekDays() {
        return this.weekDays;
    }
    
    public void setWeekDays(String weekDays) {
        this.weekDays = weekDays;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="one_date", length=10)
    public Date getOneDate() {
        return this.oneDate;
    }
    
    public void setOneDate(Date oneDate) {
        this.oneDate = oneDate;
    }




}


