package com.polo.blog.model;
// Generated 14/04/2018 22:35:48 by Hibernate Tools 4.3.1

import com.polo.blog.model.data.DB;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Post generated by hbm2java
 */
@Entity
@Table(name="post",catalog="blog")
public class Post  implements java.io.Serializable {

    private Integer id;
    private String titulo;
    private String conteudo;
    private LocalDate dataPub;
    private List<Arquivo> arquivos = new ArrayList<>();
    private List<Tag> tags = new ArrayList<>();

    public Post() {
        super();
    }

    @Id 
    @GeneratedValue(strategy=IDENTITY)
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="titulo", nullable=false)
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    
    @Column(name="conteudo", nullable=false, length=65535)
    public String getConteudo() {
        return this.conteudo;
    }
    
    public void setConteudo(String conteudo) {
        this.conteudo = conteudo;
    }

    
    @Column(name="data_pub", nullable=false, length=19)
    public LocalDate getDataPub() {
        return this.dataPub;
    }
    
    public void setDataPub(LocalDate dataPub) {
        this.dataPub = dataPub;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="post")
    public List<Arquivo> getArquivos() {
        return this.arquivos;
    }
    
    public void setArquivos(List<Arquivo> arquivos) {
        this.arquivos = arquivos;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="post_tag", catalog="blog", joinColumns = { 
    @JoinColumn(name="post_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
    @JoinColumn(name="tag_id", nullable=false, updatable=false) })
    public List<Tag> getTags() {
        return this.tags;
    }
    
    public void setTags(List<Tag> tags) {
        this.tags = tags;
    }

    public void save(){
        if (id == null)
            DB.insert(this);
        else
            DB.update(this);
    }
    
    public void delete(){
        if (id != null)
            DB.delete(this);
    }
    
    public static List<Post> getAll(){
        return (List<Post>)DB.getAll(Post.class);
    }

    @Override
    public String toString(){
        return "Post - id: "+id+" titulo: "+titulo+" publicado em: "+dataPub;
    }
    
}


