package com.polo.blog.model;
// Generated 14/04/2018 22:35:48 by Hibernate Tools 4.3.1


import com.polo.blog.model.data.Model;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Tag generated by hbm2java
 */
@Entity
@Table(name="tag",catalog="blog")
public class Tag  extends Model {

    private String nome;
    private List<Post> posts = new ArrayList<>();

    public Tag() {
        super();
    }
   
    @Column(name="nome", nullable=false, length=20)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    @ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="post_tag", catalog="blog", joinColumns = { 
    @JoinColumn(name="tag_id", nullable=false, updatable=false) }, inverseJoinColumns = { 
    @JoinColumn(name="post_id", nullable=false, updatable=false) })
    public List<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(List<Post> posts) {
        this.posts = posts;
    }

}


