package br.com.pinmyhelp.model;
// Generated 17/05/2018 15:02:51 by Hibernate Tools 4.3.1


import br.com.pinmyhelp.model.data.Model;
import br.com.pinmyhelp.model.types.GeoLocation;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Disponibility generated by hbm2java
 */
@javax.persistence.Entity
@Table(name="disponibility",catalog="pinmyhelp")
public class Disponibility  extends Model {

    private Voluntary voluntary;
    private Date startDateTime;
    private Date endDateTime;
    private GeoLocation location;

    public Disponibility() {
    }

    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="voluntary_id", nullable=false)
    public Voluntary getVoluntary() {
        return this.voluntary;
    }
    
    public void setVoluntary(Voluntary voluntary) {
        this.voluntary = voluntary;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_date_time", nullable=false, length=19)
    public Date getStartDateTime() {
        return this.startDateTime;
    }
    
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_date_time", length=19)
    public Date getEndDateTime() {
        return this.endDateTime;
    }
    
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }

    /**
     * @return the location
     */
    @Embedded
    @AttributeOverrides(value = {
        @AttributeOverride(name = "x", column = @Column(name = "x")),
        @AttributeOverride(name = "y", column = @Column(name = "y"))
    })
    public GeoLocation getLocation() {
        return location;
    }

    /**
     * @param location the location to set
     */
    public void setLocation(GeoLocation location) {
        this.location = location;
    }

}